apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "chart.fullname" . }}
  labels:
    app: {{ template "chart.fullname" . }}
    chart: {{ template "chart.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  template:
    metadata:
      labels:
        app: {{ template "chart.fullname" . }}
        chart: {{ template "chart.chart" . }}
        release: {{ .Release.Name | quote }}
    spec:
      containers:
      - name: {{ template "chart.fullname" . }}
        image: {{ template "chart.image" . }}
        ports:
        - containerPort: 80
        env:
        {{- range $key, $value := .Values.deployment.env }}
        - name: "{{ $key }}"
          value: "{{ $value }}"
        {{- end }}
